export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const CARGAR_PRODUCTOS = "CARGAR_PRODUCTOS";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const DELETE_PRODUCTO = "DELETE_PRODUCTO";
